<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Event;
use App\Models\Category;
use App\Models\User;
use Carbon\Carbon;

class EventSeeder extends Seeder
{
    public function run(): void
    {
        $organizers = User::where('role', 'organizer')->get();
        $categories = Category::all();

        $events = [
            [
                'title' => 'Tech Conference 2024',
                'description' => 'Join us for the biggest technology conference of the year! Featuring keynote speakers, workshops, and networking opportunities.',
                'venue' => 'Convention Center',
                'address' => '123 Main Street',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'postal_code' => '94102',
                'latitude' => 37.7749,
                'longitude' => -122.4194,
                'start_date' => Carbon::now()->addDays(30),
                'end_date' => Carbon::now()->addDays(32),
                'registration_deadline' => Carbon::now()->addDays(25),
                'capacity' => 500,
                'price' => 299.00,
                'currency' => 'USD',
                'status' => 'published',
                'is_featured' => true,
                'requires_approval' => false,
                'tags' => ['technology', 'conference', 'networking'],
                'category_slugs' => ['technology', 'business'],
            ],
            [
                'title' => 'Art Exhibition Opening',
                'description' => 'Experience contemporary art from local and international artists. Wine and light refreshments will be served.',
                'venue' => 'Modern Art Gallery',
                'address' => '456 Art District',
                'city' => 'New York',
                'state' => 'NY',
                'country' => 'USA',
                'postal_code' => '10001',
                'latitude' => 40.7128,
                'longitude' => -74.0060,
                'start_date' => Carbon::now()->addDays(15),
                'end_date' => Carbon::now()->addDays(15)->addHours(3),
                'registration_deadline' => Carbon::now()->addDays(10),
                'capacity' => 100,
                'price' => 0.00,
                'currency' => 'USD',
                'status' => 'published',
                'is_featured' => true,
                'requires_approval' => true,
                'tags' => ['art', 'exhibition', 'culture'],
                'category_slugs' => ['arts-culture'],
            ],
            [
                'title' => 'Fitness Bootcamp',
                'description' => 'High-intensity fitness bootcamp for all levels. Bring water and a towel!',
                'venue' => 'Central Park',
                'address' => 'Central Park, Great Lawn',
                'city' => 'New York',
                'state' => 'NY',
                'country' => 'USA',
                'postal_code' => '10024',
                'latitude' => 40.7829,
                'longitude' => -73.9654,
                'start_date' => Carbon::now()->addDays(7),
                'end_date' => Carbon::now()->addDays(7)->addHours(2),
                'registration_deadline' => Carbon::now()->addDays(5),
                'capacity' => 50,
                'price' => 25.00,
                'currency' => 'USD',
                'status' => 'published',
                'is_featured' => false,
                'requires_approval' => false,
                'tags' => ['fitness', 'bootcamp', 'outdoor'],
                'category_slugs' => ['sports-fitness', 'health-wellness'],
            ],
            [
                'title' => 'Business Networking Mixer',
                'description' => 'Connect with fellow professionals and entrepreneurs. Great opportunity for business development.',
                'venue' => 'Downtown Hotel',
                'address' => '789 Business Ave',
                'city' => 'Chicago',
                'state' => 'IL',
                'country' => 'USA',
                'postal_code' => '60601',
                'latitude' => 41.8781,
                'longitude' => -87.6298,
                'start_date' => Carbon::now()->addDays(20),
                'end_date' => Carbon::now()->addDays(20)->addHours(3),
                'registration_deadline' => Carbon::now()->addDays(15),
                'capacity' => 200,
                'price' => 50.00,
                'currency' => 'USD',
                'status' => 'published',
                'is_featured' => false,
                'requires_approval' => false,
                'tags' => ['networking', 'business', 'professional'],
                'category_slugs' => ['business'],
            ],
            [
                'title' => 'Cooking Workshop: Italian Cuisine',
                'description' => 'Learn to cook authentic Italian dishes with our professional chef. All ingredients included.',
                'venue' => 'Culinary School',
                'address' => '321 Chef Street',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'country' => 'USA',
                'postal_code' => '90210',
                'latitude' => 34.0522,
                'longitude' => -118.2437,
                'start_date' => Carbon::now()->addDays(45),
                'end_date' => Carbon::now()->addDays(45)->addHours(4),
                'registration_deadline' => Carbon::now()->addDays(40),
                'capacity' => 30,
                'price' => 75.00,
                'currency' => 'USD',
                'status' => 'published',
                'is_featured' => false,
                'requires_approval' => false,
                'tags' => ['cooking', 'italian', 'workshop'],
                'category_slugs' => ['food-drink', 'education'],
            ],
            [
                'title' => 'Music Festival 2024',
                'description' => 'Three days of amazing music featuring top artists from around the world. Food trucks and vendors available.',
                'venue' => 'Music Park',
                'address' => '555 Festival Grounds',
                'city' => 'Austin',
                'state' => 'TX',
                'country' => 'USA',
                'postal_code' => '73301',
                'latitude' => 30.2672,
                'longitude' => -97.7431,
                'start_date' => Carbon::now()->addDays(60),
                'end_date' => Carbon::now()->addDays(62),
                'registration_deadline' => Carbon::now()->addDays(55),
                'capacity' => 5000,
                'price' => 150.00,
                'currency' => 'USD',
                'status' => 'published',
                'is_featured' => true,
                'requires_approval' => false,
                'tags' => ['music', 'festival', 'entertainment'],
                'category_slugs' => ['entertainment', 'arts-culture'],
            ],
            [
                'title' => 'Web Development Workshop',
                'description' => 'Learn modern web development techniques including React, Node.js, and database design. Perfect for beginners and intermediate developers.',
                'venue' => 'Tech Hub',
                'address' => '789 Innovation Drive',
                'city' => 'Seattle',
                'state' => 'WA',
                'country' => 'USA',
                'postal_code' => '98101',
                'latitude' => 47.6062,
                'longitude' => -122.3321,
                'start_date' => Carbon::now()->addDays(12),
                'end_date' => Carbon::now()->addDays(12)->addHours(6),
                'registration_deadline' => Carbon::now()->addDays(8),
                'capacity' => 40,
                'price' => 89.00,
                'currency' => 'USD',
                'status' => 'published',
                'is_featured' => false,
                'requires_approval' => false,
                'tags' => ['programming', 'workshop', 'education'],
                'category_slugs' => ['technology', 'education'],
            ],
            [
                'title' => 'Yoga Retreat Weekend',
                'description' => 'A peaceful weekend retreat focusing on yoga, meditation, and mindfulness. All levels welcome.',
                'venue' => 'Mountain View Resort',
                'address' => '123 Serenity Lane',
                'city' => 'Boulder',
                'state' => 'CO',
                'country' => 'USA',
                'postal_code' => '80301',
                'latitude' => 40.0150,
                'longitude' => -105.2705,
                'start_date' => Carbon::now()->addDays(25),
                'end_date' => Carbon::now()->addDays(27),
                'registration_deadline' => Carbon::now()->addDays(20),
                'capacity' => 25,
                'price' => 199.00,
                'currency' => 'USD',
                'status' => 'published',
                'is_featured' => false,
                'requires_approval' => true,
                'tags' => ['yoga', 'retreat', 'wellness'],
                'category_slugs' => ['health-wellness', 'sports-fitness'],
            ],
            [
                'title' => 'Startup Pitch Competition',
                'description' => 'Watch innovative startups pitch their ideas to a panel of investors. Great networking opportunity for entrepreneurs.',
                'venue' => 'Innovation Center',
                'address' => '456 Startup Street',
                'city' => 'San Francisco',
                'state' => 'CA',
                'country' => 'USA',
                'postal_code' => '94105',
                'latitude' => 37.7749,
                'longitude' => -122.4194,
                'start_date' => Carbon::now()->addDays(18),
                'end_date' => Carbon::now()->addDays(18)->addHours(4),
                'registration_deadline' => Carbon::now()->addDays(12),
                'capacity' => 150,
                'price' => 35.00,
                'currency' => 'USD',
                'status' => 'published',
                'is_featured' => true,
                'requires_approval' => false,
                'tags' => ['startup', 'pitch', 'entrepreneurship'],
                'category_slugs' => ['business', 'technology'],
            ],
            [
                'title' => 'Photography Masterclass',
                'description' => 'Professional photography workshop covering composition, lighting, and post-processing techniques.',
                'venue' => 'Art Studio Gallery',
                'address' => '321 Creative Avenue',
                'city' => 'Portland',
                'state' => 'OR',
                'country' => 'USA',
                'postal_code' => '97201',
                'latitude' => 45.5152,
                'longitude' => -122.6784,
                'start_date' => Carbon::now()->addDays(35),
                'end_date' => Carbon::now()->addDays(35)->addHours(5),
                'registration_deadline' => Carbon::now()->addDays(30),
                'capacity' => 20,
                'price' => 125.00,
                'currency' => 'USD',
                'status' => 'published',
                'is_featured' => false,
                'requires_approval' => false,
                'tags' => ['photography', 'workshop', 'creative'],
                'category_slugs' => ['arts-culture', 'education'],
            ],
            [
                'title' => 'Charity Fundraiser Gala',
                'description' => 'Elegant evening gala to raise funds for local children\'s hospital. Dinner, entertainment, and silent auction included.',
                'venue' => 'Grand Ballroom Hotel',
                'address' => '999 Charity Boulevard',
                'city' => 'Miami',
                'state' => 'FL',
                'country' => 'USA',
                'postal_code' => '33101',
                'latitude' => 25.7617,
                'longitude' => -80.1918,
                'start_date' => Carbon::now()->addDays(50),
                'end_date' => Carbon::now()->addDays(50)->addHours(5),
                'registration_deadline' => Carbon::now()->addDays(45),
                'capacity' => 300,
                'price' => 200.00,
                'currency' => 'USD',
                'status' => 'published',
                'is_featured' => true,
                'requires_approval' => false,
                'tags' => ['charity', 'gala', 'fundraising'],
                'category_slugs' => ['community', 'arts-culture'],
            ],
            [
                'title' => 'Digital Marketing Workshop',
                'description' => 'Learn the latest digital marketing strategies and tools for business growth.',
                'venue' => 'Marketing Hub',
                'address' => '456 Digital Street',
                'city' => 'Austin',
                'state' => 'TX',
                'country' => 'USA',
                'postal_code' => '73301',
                'latitude' => 30.2672,
                'longitude' => -97.7431,
                'start_date' => Carbon::now()->addDays(25),
                'end_date' => Carbon::now()->addDays(25)->addHours(6),
                'registration_deadline' => Carbon::now()->addDays(20),
                'capacity' => 40,
                'price' => 85.00,
                'currency' => 'USD',
                'status' => 'published',
                'is_featured' => false,
                'requires_approval' => false,
                'tags' => ['marketing', 'digital', 'workshop'],
                'category_slugs' => ['business-networking', 'technology'],
            ],
            [
                'title' => 'Artisan Craft Fair',
                'description' => 'Discover unique handmade crafts from local artisans and makers.',
                'venue' => 'Community Center',
                'address' => '321 Craft Lane',
                'city' => 'Portland',
                'state' => 'OR',
                'country' => 'USA',
                'postal_code' => '97201',
                'latitude' => 45.5152,
                'longitude' => -122.6784,
                'start_date' => Carbon::now()->addDays(30),
                'end_date' => Carbon::now()->addDays(30)->addHours(8),
                'registration_deadline' => Carbon::now()->addDays(25),
                'capacity' => 200,
                'price' => 0.00,
                'currency' => 'USD',
                'status' => 'published',
                'is_featured' => true,
                'requires_approval' => false,
                'tags' => ['crafts', 'artisan', 'community'],
                'category_slugs' => ['arts-culture', 'community'],
            ],
            [
                'title' => 'Data Science Conference 2024',
                'description' => 'Explore the latest trends in data science, machine learning, and AI applications.',
                'venue' => 'Tech Convention Hall',
                'address' => '789 Data Drive',
                'city' => 'Seattle',
                'state' => 'WA',
                'country' => 'USA',
                'postal_code' => '98101',
                'latitude' => 47.6062,
                'longitude' => -122.3321,
                'start_date' => Carbon::now()->addDays(35),
                'end_date' => Carbon::now()->addDays(35)->addHours(8),
                'registration_deadline' => Carbon::now()->addDays(30),
                'capacity' => 300,
                'price' => 150.00,
                'currency' => 'USD',
                'status' => 'published',
                'is_featured' => true,
                'requires_approval' => false,
                'tags' => ['data-science', 'ai', 'machine-learning'],
                'category_slugs' => ['technology', 'education'],
            ],
            [
                'title' => 'Sustainability Summit',
                'description' => 'Join environmental leaders and sustainability experts for a day of learning and networking.',
                'venue' => 'Green Convention Center',
                'address' => '555 Eco Way',
                'city' => 'Denver',
                'state' => 'CO',
                'country' => 'USA',
                'postal_code' => '80202',
                'latitude' => 39.7392,
                'longitude' => -104.9903,
                'start_date' => Carbon::now()->addDays(40),
                'end_date' => Carbon::now()->addDays(40)->addHours(6),
                'registration_deadline' => Carbon::now()->addDays(35),
                'capacity' => 150,
                'price' => 75.00,
                'currency' => 'USD',
                'status' => 'published',
                'is_featured' => false,
                'requires_approval' => false,
                'tags' => ['sustainability', 'environment', 'green'],
                'category_slugs' => ['community', 'education'],
            ],
        ];

        foreach ($events as $eventData) {
            $organizer = $organizers->random();
            $categorySlugs = $eventData['category_slugs'];
            unset($eventData['category_slugs']);

            $event = Event::create(array_merge($eventData, [
                'organizer_id' => $organizer->id,
                'slug' => \Illuminate\Support\Str::slug($eventData['title']),
            ]));

            $eventCategories = $categories->whereIn('slug', $categorySlugs);
            $event->categories()->attach($eventCategories->pluck('id'));
        }
    }
}
